### ISSUE TITLE
Crashes while encoding image

### ISSUE THREAD

**Issue by greensea** [Kagami/go-avif#14]
Encoding the attached image cause crash.

Encode options
```
err = avif.Encode(&out, img, &avif.Options{Quality: 52, Threads: 0, Speed: 6})
```

Stack:
```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7f963f775b64]

runtime stack:
runtime.throw({0x5aed54, 0x7f95f8000c48})
	/usr/local/go/src/runtime/panic.go:1198 +0x71
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:719 +0x396

goroutine 1 [syscall]:
runtime.cgocall(0x57d670, 0xc00005fc40)
	/usr/local/go/src/runtime/cgocall.go:156 +0x5c fp=0xc00005fc18 sp=0xc00005fbe0 pc=0x40db9c
github.com/kagami/go-avif._Cfunc_avif_encode_frame(0xc001e18964, 0xc000012010, 0xc0000124f0)
	_cgo_gotypes.go:97 +0x4c fp=0xc00005fc40 sp=0xc00005fc18 pc=0x4d782c
github.com/kagami/go-avif.Encode.func3(0xc001e18960, 0x13, 0x3adc)
	/home/gs/go/src/github.com/kagami/go-avif/avif.go:191 +0x87 fp=0xc00005fc88 sp=0xc00005fc40 pc=0x4d85c7
github.com/kagami/go-avif.Encode({0x5ccf00, 0xc00010c210}, {0x5cee00, 0xc000092080}, 0x0)
	/home/gs/go/src/github.com/kagami/go-avif/avif.go:191 +0x58b fp=0xc00005fe68 sp=0xc00005fc88 pc=0x4d818b
main.main()
	/tmp/test.go:42 +0x367 fp=0xc00005ff80 sp=0xc00005fe68 pc=0x4d9207
runtime.main()
	/usr/local/go/src/runtime/proc.go:255 +0x227 fp=0xc00005ffe0 sp=0xc00005ff80 pc=0x43e5a7
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00005ffe8 sp=0xc00005ffe0 pc=0x468fe1
exit status 2

```

![008diOL4gy1grixj32sbrj30ndcn4kjl](https://user-images.githubusercontent.com/619187/141887117-66384e6b-bc2f-4e66-ac16-5c8a57c1cd51.jpg)

Image source: https://wx1.sinaimg.cn/large/008diOL4gy1grixj32sbrj30ndcn4kjl.jpg

**Comment by emilpriver** [comment]
I get the same error. Could be a memory error.
